version: '3.9'

services:
  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
      MONGO_INITDB_DATABASE: dogs
    volumes:
      - mongodata:/data/db

  web:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://mongo:Passw0rd@mongodb:27017/dogs?authSource=admin"

volumes:
  mongodata:
